const mix = require('laravel-mix');
const fs = require('fs');
const path = require('path');

const modulePublicPath = 'public';
const webpackOutputPublicPath = '/assets/simvector/'; // Define the prefix

// Add global PostCSS options
mix.options({
    postCss: [
        require('@tailwindcss/postcss'),
        require('autoprefixer'),
    ],
});

mix.webpackConfig({
    output: {
        publicPath: webpackOutputPublicPath, // Use the defined prefix
    },
    watchOptions: {
        ignored: [
            path.resolve(__dirname, modulePublicPath, 'mix-manifest.json'),
            path.resolve(__dirname, modulePublicPath, 'meta.json'),
        ],
    },
});
mix.setPublicPath(modulePublicPath)
//  .js('Resources/assets/admin/admin.js', 'admin/js/admin.js')
  .js('Resources/assets/frontend/flightsearch/flightsearch.js', 'frontend/js/flightsearch.js')
  //.sass('Resources/assets/admin/assets/app.scss', 'admin/css/app.css') // Add SCSS compilation
  //.postCss('Resources/assets/admin/assets/admin.css', 'admin/css/admin.css') // Use global PostCSS options
  .vue({
  })
  .version(); // Configure versioning

mix.after(() => {
//    // Construct the path to the module-specific mix-manifest.json
//    const manifestPath = path.resolve(__dirname, modulePublicPath, 'mix-manifest.json');
//    
//    // Check if the manifest file exists
//    if (!fs.existsSync(manifestPath)) {
//      console.error(`Error: mix-manifest.json not found at ${manifestPath}. Ensure the Mix build process completed successfully and created the manifest file.`);
//      process.exit(1); // Exit if manifest is not found
//    }
//
//    // Read the original manifest generated by Mix
//    const originalManifestJson = fs.readFileSync(manifestPath, 'utf8');
//    const originalManifest = JSON.parse(originalManifestJson);
//
//    // Define the desired prefix, ensuring it doesn't have a trailing slash for concatenation
//    let desiredPrefix = webpackOutputPublicPath; // e.g., /assets/chtrips/
//    if (desiredPrefix.endsWith('/')) {
//        desiredPrefix = desiredPrefix.slice(0, -1); // e.g., /assets/chtrips
//    }
//
//    const newManifest = {};
//    for (const originalKey in originalManifest) {
//      if (originalManifest.hasOwnProperty(originalKey)) {
//        const originalValue = originalManifest[originalKey];
//        let newKey = originalKey;
//
//        // Check if the key already starts with the full desired prefix.
//        // Keys from Mix are typically like /js/app.js or /css/app.css.
//        // We want them to be /assets/chtrips/js/app.js.
//        const expectedKeyPrefix = desiredPrefix + '/'; // e.g., /assets/chtrips/
//        
//        if (!originalKey.startsWith(expectedKeyPrefix) && desiredPrefix !== '') {
//            // Prepend the prefix. Ensure originalKey starts with a slash if it doesn't,
//            // to correctly join with desiredPrefix.
//            const normalizedOriginalKey = originalKey.startsWith('/') ? originalKey : '/' + originalKey;
//            newKey = desiredPrefix + normalizedOriginalKey;
//        }
//        // Values are assumed to be correctly prefixed by Mix's webpackConfig.output.publicPath setting.
//        newManifest[newKey] = desiredPrefix + originalValue; // Ensure this line correctly reflects your manifest goals. If originalValue is already prefixed, you might only need: newManifest[newKey] = originalValue;
//      }
//    }
//    
//    const newManifestJson = JSON.stringify(newManifest, null, 2);
//
//    // Write the modified manifest back only if its content has actually changed.
//    if (originalManifestJson !== newManifestJson) {
//      fs.writeFileSync(manifestPath, newManifestJson);
//      console.log('mix-manifest.json updated with prefixed keys.');
//    } else {
//      console.log('mix-manifest.json keys are already correctly prefixed or no changes needed. No update made.');
//    }
//    
//    // Generate meta.json using the newManifest (which has prefixed keys and original values)
//    const metaJsonPath = path.resolve(__dirname, modulePublicPath, 'meta.json');
//    // The content for meta.json is the same as the new (potentially updated) mix-manifest.json
//    const metaJsonContent = newManifestJson; 
//
//    let writeMetaJson = true;
//    if (fs.existsSync(metaJsonPath)) {
//        const existingMetaJsonContent = fs.readFileSync(metaJsonPath, 'utf8');
//        if (existingMetaJsonContent === metaJsonContent) {
//            writeMetaJson = false;
//        }
//    }
  });
